#!/usr/bin/env python3
"""
gen_array.py — generate pcn_array and pcn_module SPICE subcircuits for any N_ROWS × N_COLS.

Usage:
  python3 gen_array.py <N_ROWS> <N_COLS>

Outputs:
  pcn_array_{N_ROWS}x{N_COLS}.spice   — flat MAC array subcircuit
  pcn_module_{N_ROWS}x{N_COLS}.spice  — complete module (array + error path)

The design scales: change N_ROWS and N_COLS, regenerate, same layer_link and chip top
wiring still applies because the inter-module port names follow the same convention.
"""

import sys
from textwrap import dedent

def gen_array(nr, nc):
    lines = []
    lines.append(f"* Generated by gen_array.py — DO NOT EDIT by hand.")
    lines.append(f"* Regenerate: python3 gen_array.py {nr} {nc}")
    lines.append(f"* PCN weight array: {nr} rows × {nc} columns = {nr*nc} MAC cells.")
    lines.append(f"*")
    lines.append(f"* Port convention:")
    lines.append(f"*   inp_col_c / inn_col_c  — differential column inputs (c = 0..{nc-1})")
    lines.append(f"*   iout_row_r             — row KCL accumulation bus (r = 0..{nr-1})")
    lines.append(f"*   we_row_r               — Hebbian write enable for row r (from hebb_ctrl)")
    lines.append(f"*   v_post_r               — post-synaptic signal for row r (from precision_gate.ierr_dig)")
    lines.append(f"*   vcm vdd vss")
    lines.append(f"*")
    lines.append(f"* Internal nodes:")
    lines.append(f"*   vw_r_c                 — weight capacitor voltage for cell [r][c]")
    lines.append(f"*   iwrite_r_c             — Hebbian update current (hebbian_mult → mac_cell.iwrite)")
    lines.append("")

    # Build port list
    col_inp = " ".join(f"inp_col_{c} inn_col_{c}" for c in range(nc))
    row_out = " ".join(f"iout_row_{r}" for r in range(nr))
    we      = " ".join(f"we_row_{r}" for r in range(nr))
    vpost   = " ".join(f"v_post_{r}" for r in range(nr))
    subckt  = f".subckt pcn_array_{nr}x{nc}"
    ports   = f"+ {col_inp}\n+ {row_out}\n+ {we}\n+ {vpost}\n+ vcm vdd vss"
    lines.append(subckt)
    lines.append(ports)
    lines.append("")

    lines.append("* ── MAC cells ────────────────────────────────────────────────────────────────")
    lines.append("* X_mac_r_c  iout_row_r  inp_col_c  inn_col_c  vw_r_c  iwrite_r_c  we_row_r  vdd vss  mac_cell")
    for r in range(nr):
        for c in range(nc):
            lines.append(
                f"X_mac_{r}_{c}"
                f"  iout_row_{r}"
                f"  inp_col_{c}"
                f"  inn_col_{c}"
                f"  vw_{r}_{c}"
                f"  iwrite_{r}_{c}"
                f"  we_row_{r}"
                f"  vdd vss"
                f"  mac_cell"
            )
        lines.append("")

    lines.append("* ── Hebbian multipliers ──────────────────────────────────────────────────────")
    lines.append("* X_hebb_r_c  iwrite_r_c  v_pre(=inp_col_c)  v_post_r  vcm  vdd vss  hebbian_mult")
    for r in range(nr):
        for c in range(nc):
            lines.append(
                f"X_hebb_{r}_{c}"
                f"  iwrite_{r}_{c}"
                f"  inp_col_{c}"   # v_pre: single-ended column input voltage
                f"  v_post_{r}"    # v_post: ierr_dig from precision_gate (HIGH when update fires)
                f"  vcm vdd vss"
                f"  hebbian_mult"
            )
        lines.append("")

    lines.append(f".ends pcn_array_{nr}x{nc}")
    return "\n".join(lines)


def gen_module(nr, nc):
    # §40.5/§45 scaling rule: r_err = 100kΩ×(4/nc), w_mpg = 2µm×(nc/4)
    # Maintains τ_KCL=28ns and V_trip≈VDD/2 invariants across array sizes.
    r_err_ohm = 100000 * 4 / nc
    r_err_str = f"{r_err_ohm/1000:.4g}k"   # "100k", "25k", "12.5k"
    w_mpg = 2 * nc / 4                      # µm: nc=4→2, nc=16→8, nc=32→16
    w_mpg_str = f"{w_mpg:.4g}"
    # §48 floor: w_floor fixed at 0.5µm — V_floor = I_floor×R_err shrinks as nc grows.
    # §25 I_bias: NOT at KCL bus level — see §49 for analysis and alternative placement.
    w_floor_str = "0.5"                     # fixed — see §48.6

    lines = []
    lines.append(f"* Generated by gen_array.py — DO NOT EDIT by hand.")
    lines.append(f"* Regenerate: python3 gen_array.py {nr} {nc}")
    lines.append(f"* PCN module: {nr}×{nc} array + current_sub + precision_gate for each row.")
    lines.append(f"* Scaling: r_err={r_err_str} (τ_KCL=28ns), w_mpg={w_mpg_str}µm (V_trip≈VDD/2), w_floor=0.5µm (§48 fixed)")
    lines.append(f"*")
    lines.append(f"* Analog signal flow (one column per row r):")
    lines.append(f"*   inp_col_c/inn_col_c → mac array → iout_row_r")
    lines.append(f"*   iout_row_r + i_pred_r → current_sub_r → i_err_r")
    lines.append(f"*   i_err_r → precision_gate_r → ierr_dig_r  (→ digital hebb_ctrl.ierr[r])")
    lines.append(f"*                              ↘ v_post_r    (→ array hebbian_mult)")
    lines.append(f"*")
    lines.append(f"* Ports:")
    lines.append(f"*   inp_col_0..{nc-1}, inn_col_0..{nc-1}  — column differential inputs")
    lines.append(f"*   iout_row_0..{nr-1} — KCL accumulation bus outputs (exposed for layer_link)")
    lines.append(f"*                        connects to layer_link ascending input and descending gate")
    lines.append(f"*   i_pred_0..{nr-1}   — prediction current inputs (from layer above via layer_link)")
    lines.append(f"*                        connect as sinking load on i_err node (see current_sub)")
    lines.append(f"*   ierr_dig_0..{nr-1} — digital error flags out to hebb_ctrl (HIGH = error > threshold)")
    lines.append(f"*   we_row_0..{nr-1}   — Hebbian write enables in from hebb_ctrl.we_out")
    lines.append(f"*   vpi_0..{nr-1}      — precision threshold voltages (one per row; from bias_gen or DAC)")
    lines.append(f"*   vbias_p, vbias_n, vcm — shared bias rails from bias_gen")
    lines.append(f"*   vdd, vss")
    lines.append("")

    col_inp  = " ".join(f"inp_col_{c} inn_col_{c}" for c in range(nc))
    iout_row = " ".join(f"iout_row_{r}" for r in range(nr))
    i_pred   = " ".join(f"i_pred_{r}" for r in range(nr))
    ierr_out = " ".join(f"ierr_dig_{r}" for r in range(nr))
    we_in    = " ".join(f"we_row_{r}" for r in range(nr))
    vpi      = " ".join(f"vpi_{r}" for r in range(nr))

    lines.append(f".subckt pcn_module_{nr}x{nc}")
    lines.append(f"+ {col_inp}")
    lines.append(f"+ {iout_row}")
    lines.append(f"+ {i_pred}")
    lines.append(f"+ {ierr_out}")
    lines.append(f"+ {we_in}")
    lines.append(f"+ {vpi}")
    lines.append(f"+ vbias_p vbias_n vcm vdd vss")
    lines.append("")

    # Array instance — v_post_r driven by precision_gate.ierr_dig_r (same node name)
    row_out = " ".join(f"iout_row_{r}" for r in range(nr))
    we      = " ".join(f"we_row_{r}" for r in range(nr))
    vpost   = " ".join(f"ierr_dig_{r}" for r in range(nr))  # same node as ierr_dig output
    lines.append(f"* ── Array instance ───────────────────────────────────────────────────────────")
    lines.append(f"Xarray")
    lines.append(f"+ {col_inp}")
    lines.append(f"+ {row_out}")
    lines.append(f"+ {we}")
    lines.append(f"+ {vpost}")
    lines.append(f"+ vcm vdd vss")
    lines.append(f"+ pcn_array_{nr}x{nc}")
    lines.append("")

    lines.append(f"* ── current_sub: one per row ─────────────────────────────────────────────────")
    lines.append(f"* X_csub_r  i_actual=iout_row_r  i_pred=i_pred_r  i_err=i_err_r  vdd vss  r_err={r_err_str}")
    for r in range(nr):
        lines.append(
            f"X_csub_{r}"
            f"  iout_row_{r}"
            f"  i_pred_{r}"
            f"  i_err_{r}"
            f"  vdd vss"
            f"  current_sub"
            f"  r_err={r_err_str}"
        )
    lines.append("")

    lines.append(f"* ── precision_gate: one per row ──────────────────────────────────────────────")
    lines.append(f"* X_pgate_r  i_in=i_err_r  vpi=vpi_r  i_out=i_pout_r  ierr_dig=ierr_dig_r  vdd vss")
    lines.append(f"*            w_mpg={w_mpg_str}µm  w_floor=0.5µm")
    for r in range(nr):
        lines.append(
            f"X_pgate_{r}"
            f"  i_err_{r}"
            f"  vpi_{r}"
            f"  i_pout_{r}"
            f"  ierr_dig_{r}"    # this IS v_post_r (same node used by array above)
            f"  vdd vss"
            f"  precision_gate"
            f"  w_mpg={w_mpg_str}"
            f"  w_floor={w_floor_str}"
        )
    lines.append("")

    lines.append(f".ends pcn_module_{nr}x{nc}")
    return "\n".join(lines)


def gen_routing_link(nr):
    """
    Generate layer_link_route_{nr}.spice — ascending source-follower path (nr rows)
    plus a full nr×nr learned routing matrix on the descending path.

    Ascending path (unchanged from layer_link_row):
      iout_lower_r  →  XMSF/XMTAIL source follower  →  inp_upper_r

    Descending routing matrix (new — replaces single XMPRED):
      For each destination row d and source row s:
        routing_cell[d][s]:  XMPRED (gate=Vw_route_d_s) sinks from i_pred[d]
                             Cw_route_d_s  (routing weight capacitor, 200fF default)
                             MN4_r_d_s     (access transistor, gate=we_route)
        hebbian_mult[d][s]:  v_pre = inp_upper_s  (ascending SF output of source s)
                             vcm   = vcm_route     (~0.15V — below SF balance ≈0.29V for 16×32)
                             v_post = ierr_dig_d   (destination error signal)
                             i_out → iwrite_route_d_s → MN4_r_d_s → Cw_route_d_s

    The routing Hebbian rule:
      ΔVw_route[d,s] ∝ (inp_upper_s − vcm_route) × ierr_dig_d
      Strengthens route d←s when source s is active AND destination d has error.
      Weakens it when source s is below baseline (LTD for uncorrelated sources).

    NOTE on SF operating range and LTD/LTP:
      For 16×32 arrays V(iout_lower)≈1.031V (regulated) → SF output ≈ 0.29V < Vth(0.48V).
      LTD mechanism: vcm_route must be > Vth (e.g. 0.65V) so MN6 (gate=vcm_route) is ON
        and draws all tail current → i_out node pulled to VSS → XMN4_r discharges Cw_route.
        ΔVw ≈ −45mV/pulse (verified simulation §43).
      LTP mechanism: requires inp_upper (SF output) > vcm_route AND > Vth(0.48V).
        For 16×32 with SF balance=0.29V, LTP is not achievable — set vcm_route ≥ 0.50V and
        redesign SF circuit to lift output above 0.48V (lower XMTAIL vbias_n, or resize XMSF).
      LTP/LTD balance point: vcm_route ≈ SF balance output (≈0.29V for 16×32) would give
        balanced learning IF the diff pair conducted — but at 0.29V both MN5 and MN6 are
        subthreshold and the write current is negligible.
    Set vcm_route = 0.65V for current 16×32 design to ensure LTD operates correctly.

    Routing weight capacitor: Cw_route = 200fF (same learning speed as MAC weights).
    For slower topological timescale set Cw_route = 2p in the generated file.

    Ports:
      iout_lower_0..nr-1  — lower module KCL bus outputs (→ ascending SF gates)
      inp_upper_0..nr-1   — upper module column inputs   (← ascending SF outputs)
      i_pred_0..nr-1      — lower module prediction inputs (← routing current sum)
      iout_upper_0..nr-1  — upper module KCL bus outputs (not used in routing here;
                            kept for completeness and future descending-SF variants)
      ierr_dig_0..nr-1    — lower module error flags (v_post for routing Hebbian)
      we_route            — shared routing write-enable (HIGH during topology update)
      vcm_route           — routing Hebbian reference (0.65V for 16×32: keeps MN6 above Vth)
                            Separate from vpi (precision gate ref) — same VALUE for 16×32 but
                            independent rails; change here without touching precision gate bias
      vcm_iout            — actual balanced iout OP (≈0.468V); drives reference SF gate (§72)
      vbias_n, vdd, vss
    """
    lines = []
    lines.append(f"* Generated by gen_array.py — DO NOT EDIT by hand.")
    lines.append(f"* Regenerate: python3 gen_array.py --routing {nr}")
    lines.append(f"* Routing layer link: {nr} ascending SFs + {nr}×{nr} routing matrix.")
    lines.append(f"* Routing cells: {nr*nr} XMPRED + {nr*nr} Cw_route + {nr*nr} MN4_r + {nr*nr} hebbian_mult")
    lines.append(f"*")
    lines.append(f"* See pred_code_networks.md §42 for design rationale.")
    lines.append("")

    # Port list
    def ports_for(prefix, n): return "  ".join(f"{prefix}_{i}" for i in range(n))
    lines.append(f".subckt layer_link_route_{nr}")
    lines.append(f"+ {ports_for('iout_lower', nr)}")
    lines.append(f"+ {ports_for('inp_upper',  nr)}")
    lines.append(f"+ {ports_for('i_pred',     nr)}")
    lines.append(f"+ {ports_for('iout_upper', nr)}")
    lines.append(f"+ {ports_for('ierr_dig',   nr)}")
    lines.append(f"+ we_route")
    lines.append(f"+ vcm_route vcm_upper vcm_iout vbias_n vdd vss")
    lines.append("")

    # ── Ascending PMOS source followers (§71 spatial fix) ────────────────────
    lines.append(f"* {'─'*74}")
    lines.append(f"* ASCENDING PATH: {nr} PMOS source followers  iout_lower_r → inp_upper_r")
    lines.append(f"* V(inp_upper) = V(iout_lower) + |Vgs_P| ≈ +0.65V (§71 PMOS SF fix)")
    lines.append(f"* {'─'*74}")
    for r in range(nr):
        lines.append(f"* Row {r}")
        lines.append(
            f"XMSF_{r}"
            f"   n_sf_d_{r}  iout_lower_{r}  inp_upper_{r}  vdd"
            f"   sky130_fd_pr__pfet_01v8  w=4  l=0.5"
        )
        lines.append(
            f"XMTAIL_{r}"
            f"  n_sf_d_{r}  vbias_n  vss  vss"
            f"   sky130_fd_pr__nfet_01v8  w=2  l=1"
        )
    lines.append(f"* Reference PMOS SF: vcm_iout → vcm_upper (matched shift for inn_col; §72 fix)")
    lines.append(
        f"XMSF_ref   n_sfref_d  vcm_iout  vcm_upper  vdd"
        f"   sky130_fd_pr__pfet_01v8  w=4  l=0.5"
    )
    lines.append(
        f"XMTAIL_ref n_sfref_d  vbias_n  vss  vss"
        f"   sky130_fd_pr__nfet_01v8  w=2  l=1"
    )
    lines.append("")

    # ── Routing matrix ────────────────────────────────────────────────────────
    lines.append(f"* {'─'*74}")
    lines.append(f"* DESCENDING ROUTING MATRIX: {nr}×{nr} = {nr*nr} routing cells")
    lines.append(f"*")
    lines.append(f"* For each (dest=d, src=s):")
    lines.append(f"*   XMPRED_r_d_s  — NMOS sinking from i_pred_d; gate=Vw_route_d_s")
    lines.append(f"*   Cw_route_d_s  — 200fF routing weight capacitor (increase to 2p for")
    lines.append(f"*                   10× slower topology timescale vs MAC weights)")
    lines.append(f"*   MN4_r_d_s     — access transistor; gate=we_route")
    lines.append(f"*   X_rhebb_d_s   — hebbian_mult: v_pre=inp_upper_s, vcm=vcm_route, v_post=ierr_dig_d")
    lines.append(f"*                   updates Cw_route when source active AND dest has error")
    lines.append(f"* {'─'*74}")
    lines.append("")

    for d in range(nr):
        lines.append(f"* ── Destination row {d} ── {nr} source connections ──────────────────────────")
        for s in range(nr):
            tag = f"{d}_{s}"
            lines.append(
                f"XMPRED_r_{tag}"
                f"  i_pred_{d}  vw_route_{tag}  vss  vss"
                f"  sky130_fd_pr__nfet_01v8  w=4  l=0.35"
            )
            lines.append(f"Cw_route_{tag}  vw_route_{tag}  vss  200f")
            # 10GΩ bleed: prevents floating node in DC analysis; 75µV/200ns droop (negligible)
            lines.append(f"R_bleed_{tag}  vw_route_{tag}  vss  10000meg")
            lines.append(
                f"XMN4_r_{tag}"
                f"  vw_route_{tag}  we_route  iwrite_route_{tag}  vss"
                f"  sky130_fd_pr__nfet_01v8  w=0.5  l=0.5"
            )
            # hebbian_mult: i_out  v_pre         v_post        vcm_ref    vdd vss
            # vcm_route ~0.15V: below SF balance (~0.29V for 16×32) → LTP when source active
            lines.append(
                f"X_rhebb_{tag}"
                f"  iwrite_route_{tag}"
                f"  inp_upper_{s}"    # v_pre: ascending SF output of source row s
                f"  ierr_dig_{d}"     # v_post: destination error (gates tail current)
                f"  vcm_route"        # vcm_route ~0.15V (NOT vpi; separate rail)
                f"  vdd vss"
                f"  hebbian_mult"
            )
        lines.append("")

    lines.append(f".ends layer_link_route_{nr}")
    return "\n".join(lines)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Generate PCN SPICE subcircuits")
    parser.add_argument("n_rows", type=int, help="Number of rows")
    parser.add_argument("n_cols", type=int, nargs="?", help="Number of cols (omit for routing-only)")
    parser.add_argument("--routing", action="store_true", help="Generate routing layer_link only")
    args = parser.parse_args()

    nr = args.n_rows

    if args.routing:
        # Generate routing layer_link only
        route_file = f"layer_link_route_{nr}.spice"
        with open(route_file, "w") as f:
            f.write(gen_routing_link(nr) + "\n")
        print(f"Written: {route_file}  ({nr}×{nr} = {nr*nr} routing cells)")
    else:
        if args.n_cols is None:
            parser.error("n_cols required unless --routing is specified")
        nc = args.n_cols
        arr_file = f"pcn_array_{nr}x{nc}.spice"
        mod_file = f"pcn_module_{nr}x{nc}.spice"
        with open(arr_file, "w") as f:
            f.write(gen_array(nr, nc) + "\n")
        with open(mod_file, "w") as f:
            f.write(gen_module(nr, nc) + "\n")
        print(f"Written: {arr_file}  ({nr*nc} MAC cells)")
        print(f"Written: {mod_file}  ({nr} rows × {nc} cols)")
        # Also generate matching routing link
        route_file = f"layer_link_route_{nr}.spice"
        with open(route_file, "w") as f:
            f.write(gen_routing_link(nr) + "\n")
        print(f"Written: {route_file}  ({nr}×{nr} = {nr*nr} routing cells)")
