#!/usr/bin/env python3
"""
gen_tb_4layer.py — Generate tb_pcn_4layer.spice
4-layer 16x16 chip integration testbench.

Tests:
  T1 (op-point): bias rails, ascending path voltages, descending predictions,
                 error flags at all 4 layers.
  T2 (DC sweep): raw_inp_0 swept ±50mV; signal gain measured at each layer.
  T3 (transient): Hebbian write on mod0 row 0 (short 100ns window).

Usage:  python3 gen_tb_4layer.py
Output: tb_pcn_4layer.spice
"""

NR = 16   # rows per module
NC = 16   # cols per module
NM = 4    # number of modules

# ────────────────────────────────────────────────────────────────────────────
# Nodeset values (convergence seeds)
# ────────────────────────────────────────────────────────────────────────────
VW_INIT    = 0.75   # weight capacitor initial value
VIWRITE    = 0.9    # iwrite node (floating when WE=0, Vcm is reasonable seed)
VIOUT      = 0.468  # KCL bus OP: measured 0.468V in 16×16 array (current_sub loads iout)
VINP_SF    = 1.140  # layer_link ascending PMOS SF output = V(m0_iout) + |Vgs_P| ≈ 0.468+0.669
VCMU       = 1.140  # vcm_upper = V(vcm_iout) + |Vgs_P| ≈ 0.468+0.669 (§72 fix)
VPRED      = 0.01   # descending prediction ≈ 0
VIERR      = 0.05   # i_err internal node
VIERR_DIG  = 1.8    # ierr_dig (HIGH: fires when no matching prediction)

lines = []

def w(s=""):
    lines.append(s)

# ─────────────────────────────────────────────────────────────────────────────
# Header
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* tb_pcn_4layer.spice — 4-module 16×16 chip integration testbench")
w("* Generated by gen_tb_4layer.py  — DO NOT EDIT by hand.")
w("*")
w("* Tests:")
w("*   T1 (op-point):  bias rails correct; ascending path m0→m1→m2→m3 verified;")
w("*                   descending predictions m0_pred..m2_pred non-zero; error")
w("*                   flags HIGH at top (mod3, i_pred=VSS) and variable below.")
w("*   T2 (DC sweep):  raw_inp_0 ±50mV; signal gain tracked layer by layer.")
w("*   T3 (transient): Hebbian write on mod0 row 0; ΔVw > 0 confirms LTP path.")
w("*")
w("* Circuit hierarchy:")
w("*   Stiff sources — vbias_n=0.760V, vcm=0.900V, vpi=0.650V, ncm_iout=0.468V")
w("*   ncm_iout = actual balanced iout OP (NOT Vcm=0.9V which is the input CM) (§72 fix)")
w("*   PMOS SF level shift (§71/72): V(m0_iout)≈0.468V + |Vgs_P|≈0.67V → V(m1_inp)≈1.14V")
w("*   vcm_upper per link: ref PMOS SF output ≈ ncm_iout + |Vgs_P| ≈ 1.14V (§72 fix)")
w("*   vcm_upper_01/12/23 are driven by the reference SFs inside each layer_link_16.")
w("*   Xmod0..Xmod3     — pcn_module_16x16 (array + current_sub + precision_gate)")
w("*   Xlink_01..23     — layer_link_16 (ascending PMOS SF + descending XMPRED)")
w("* =============================================================================")
w()
w(".title PCN 4-Layer 16×16 Chip Integration Testbench")
w()
w('.lib "$PDK_ROOT/sky130A/libs.tech/ngspice/sky130.lib.spice" tt')
w('.include "pcn_mac_cell.spice"')
w('.include "pcn_array_16x16.spice"')
w('.include "pcn_module_16x16.spice"')
w('.include "layer_link.spice"')
w()
w("* ── Simulation options ───────────────────────────────────────────────────────")
w(".options RELTOL=1e-3 ABSTOL=1e-12 VNTOL=1e-6 GMIN=1e-10 ITL1=300 ITL4=100")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Supplies
# ─────────────────────────────────────────────────────────────────────────────
w("* ── Supplies ─────────────────────────────────────────────────────────────────")
w("Vvdd  vdd  0  DC 1.8")
w("Vvss  vss  0  DC 0")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Bias generator
# ─────────────────────────────────────────────────────────────────────────────
w("* ── Stiff bias rails ─────────────────────────────────────────────────────────")
w("* vcm_upper_01/12/23: driven by reference SFs inside each layer_link_16 (§71).")
w("* ncm_iout: stiff 0.468V — actual balanced iout OP (measured); drives reference SF")
w("*           gate so vcm_upper tracks actual iout CM, not input Vcm (§72 fix).")
w("Vbias_n    vbias_n    0  DC 0.760")
w("Vcm_src    vcm        0  DC 0.900")
w("Vpi_src    vpi        0  DC 0.650")
w("Vcm_iout   ncm_iout   0  DC 0.468")
w()

w("* ── nc_vbias_p: floating port in all modules — tie weakly to VDD ───────────")
w("Rnc  nc_vbias_p  vdd  1000meg")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Input voltage sources
# ─────────────────────────────────────────────────────────────────────────────
w("* ── Module 0 column inputs ───────────────────────────────────────────────────")
w("Vinp0  raw_inp_0  0  DC 0.9")
for c in range(1, NC):
    w(f"Vinp{c}  raw_inp_{c}  0  DC 0.9")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Write-enable sources
# ─────────────────────────────────────────────────────────────────────────────
w("* ── Write-enable sources (all LOW; we_m0_0 gets pulse in T3) ─────────────────")
for mk in range(NM):
    for r in range(NR):
        if mk == 0 and r == 0:
            w(f"Vwe_m{mk}_{r}  we_m{mk}_{r}  0  PULSE(0 1.8 50n 1n 1n 20n 200n)")
        else:
            w(f"Vwe_m{mk}_{r}  we_m{mk}_{r}  0  DC 0")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Module 0
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Module 0 — bottom layer: raw input at vcm=0.9V")
w("* =============================================================================")
inp_ports = " ".join(f"raw_inp_{c}  vcm" for c in range(NC))
iout_ports = " ".join(f"m0_iout_{r}" for r in range(NR))
pred_ports = " ".join(f"m0_pred_{r}" for r in range(NR))
ierr_ports = " ".join(f"ierr_m0_{r}" for r in range(NR))
we_ports   = " ".join(f"we_m0_{r}" for r in range(NR))
vpi_ports  = " ".join(["vpi"] * NR)

w("Xmod0")
for chunk in [inp_ports, iout_ports, pred_ports, ierr_ports, we_ports, vpi_ports]:
    w(f"+ {chunk}")
w(f"+ nc_vbias_p  vbias_n  vcm  vdd  vss")
w("+ pcn_module_16x16")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Layer link 0→1
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Layer link 0 → 1")
w("* vcm_upper_01: ref-SF output ≈ ncm_iout + |Vgs_P| ≈ 1.14V (§72 fix)")
w("* =============================================================================")
w("Xlink_01")
w(f"+ {' '.join(f'm0_iout_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm1_inp_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm0_pred_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm1_iout_{r}' for r in range(NR))}")
w("+ vcm_upper_01 ncm_iout vbias_n vdd vss")
w("+ layer_link_16")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Module 1
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Module 1 — layer 1: m1_inp from PMOS SF (≈1.53V); inn_col = vcm_upper_01 (≈1.55V)")
w("* =============================================================================")
inp1 = " ".join(f"m1_inp_{c}  vcm_upper_01" for c in range(NC))
w("Xmod1")
w(f"+ {inp1}")
w(f"+ {' '.join(f'm1_iout_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm1_pred_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'ierr_m1_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'we_m1_{r}' for r in range(NR))}")
w(f"+ {' '.join(['vpi'] * NR)}")
w("+ nc_vbias_p  vbias_n  vcm_upper_01  vdd  vss")
w("+ pcn_module_16x16")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Layer link 1→2
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Layer link 1 → 2")
w("* vcm_upper_12: driven by Xlink_12 reference PMOS SF (§72 fix)")
w("* =============================================================================")
w("Xlink_12")
w(f"+ {' '.join(f'm1_iout_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm2_inp_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm1_pred_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm2_iout_{r}' for r in range(NR))}")
w("+ vcm_upper_12 ncm_iout vbias_n vdd vss")
w("+ layer_link_16")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Module 2
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Module 2 — layer 2: inn_col = vcm_upper_12")
w("* =============================================================================")
inp2 = " ".join(f"m2_inp_{c}  vcm_upper_12" for c in range(NC))
w("Xmod2")
w(f"+ {inp2}")
w(f"+ {' '.join(f'm2_iout_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm2_pred_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'ierr_m2_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'we_m2_{r}' for r in range(NR))}")
w(f"+ {' '.join(['vpi'] * NR)}")
w("+ nc_vbias_p  vbias_n  vcm_upper_12  vdd  vss")
w("+ pcn_module_16x16")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Layer link 2→3
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Layer link 2 → 3")
w("* vcm_upper_23: driven by Xlink_23 reference PMOS SF (§72 fix)")
w("* =============================================================================")
w("Xlink_23")
w(f"+ {' '.join(f'm2_iout_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm3_inp_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm2_pred_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'm3_iout_{r}' for r in range(NR))}")
w("+ vcm_upper_23 ncm_iout vbias_n vdd vss")
w("+ layer_link_16")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Module 3 — top
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Module 3 — top layer: i_pred=VSS (unsupervised); inn_col = vcm_upper_23")
w("* =============================================================================")
inp3 = " ".join(f"m3_inp_{c}  vcm_upper_23" for c in range(NC))
w("Xmod3")
w(f"+ {inp3}")
w(f"+ {' '.join(f'm3_iout_{r}' for r in range(NR))}")
w(f"+ {' '.join(['vss'] * NR)}")
w(f"+ {' '.join(f'ierr_m3_{r}' for r in range(NR))}")
w(f"+ {' '.join(f'we_m3_{r}' for r in range(NR))}")
w(f"+ {' '.join(['vpi'] * NR)}")
w("+ nc_vbias_p  vbias_n  vcm_upper_23  vdd  vss")
w("+ pcn_module_16x16")
w()

# ─────────────────────────────────────────────────────────────────────────────
# Nodesets
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w("* Nodesets — convergence seeds")
w("* =============================================================================")
w()
w("* Bias rails")
w(f".nodeset V(vbias_n)=0.760  V(vcm)=0.900  V(vpi)=0.650")
w()
w("* vcm_upper per link: reference PMOS SF output ≈ ncm_iout + |Vgs_P| ≈ 1.14V (§72 fix)")
w(f".nodeset V(vcm_upper_01)={VCMU}  V(vcm_upper_12)={VCMU}  V(vcm_upper_23)={VCMU}")
w(f".nodeset V(ncm_iout)=0.468")
w()
w(".nodeset V(nc_vbias_p)=1.8")
w()

w("* KCL bus nodes: all modules, all rows")
for mk in range(NM):
    ns = "  ".join(f"V(m{mk}_iout_{r})={VIOUT}" for r in range(NR))
    w(f".nodeset {ns}")
w()

w("* Layer-link ascending outputs (PMOS SF — raises voltage)")
for mk in range(1, NM):
    ns = "  ".join(f"V(m{mk}_inp_{r})={VINP_SF}" for r in range(NR))
    w(f".nodeset {ns}")
w()

w("* Descending prediction nodes")
for mk in range(NM - 1):
    ns = "  ".join(f"V(m{mk}_pred_{r})={VPRED}" for r in range(NR))
    w(f".nodeset {ns}")
w()

w("* ierr_dig (digital error outputs): seed HIGH")
for mk in range(NM):
    ns = "  ".join(f"V(ierr_m{mk}_{r})={VIERR_DIG}" for r in range(NR))
    w(f".nodeset {ns}")
w()

w("* i_err internal nodes")
for mk in range(NM):
    ns = "  ".join(f"V(xmod{mk}.i_err_{r})={VIERR}" for r in range(NR))
    w(f".nodeset {ns}")
w()

w("* Weight nodes: 4 × 16 × 16 = 1024 cells")
for mk in range(NM):
    for r in range(NR):
        ns = "  ".join(f"V(xmod{mk}.xarray.vw_{r}_{c})={VW_INIT}" for c in range(NC))
        w(f".nodeset {ns}")
w()

w("* iwrite nodes: floating when WE=0")
for mk in range(NM):
    for r in range(NR):
        ns = "  ".join(f"V(xmod{mk}.xarray.iwrite_{r}_{c})={VIWRITE}" for c in range(NC))
        w(f".nodeset {ns}")
w()

# ─────────────────────────────────────────────────────────────────────────────
# .control block
# ─────────────────────────────────────────────────────────────────────────────
w("* =============================================================================")
w(".control")
w()
w("  set filetype = ascii")
w()

# ── T1: Operating point ─────────────────────────────────────────────────────
w("  * ──────────────────────────────────────────────────────────────────────────")
w("  * T1: Operating point — all inputs at Vcm, all WE=0")
w("  * ──────────────────────────────────────────────────────────────────────────")
w('  echo ""')
w('  echo "======================================================"')
w('  echo " T1: 4-layer operating point"')
w('  echo "======================================================"')
w()
w("  op")
w()
w("  * Bias rails")
w('  echo "  --- Bias rails ---"')
w('  echo "  V(vbias_n)       = " $&V(vbias_n)       "  (target: 0.760)"')
w('  echo "  V(vcm)           = " $&V(vcm)           "  (target: 0.900)"')
w('  echo "  V(vpi)           = " $&V(vpi)           "  (target: 0.650)"')
w('  echo "  V(ncm_iout)      = " $&V(ncm_iout)      "  (balanced iout OP stiff; target 0.468)"')
w('  echo "  V(vcm_upper_01)  = " $&V(vcm_upper_01) "  (PMOS SF ref out; target ≈1.14)"')
w('  echo "  V(vcm_upper_12)  = " $&V(vcm_upper_12) "  (PMOS SF ref out; target ≈1.14)"')
w('  echo "  V(vcm_upper_23)  = " $&V(vcm_upper_23) "  (PMOS SF ref out; target ≈1.14)"')
w('  echo ""')
w()
w("  * Ascending signal path (row 0)")
w('  echo "  --- Ascending signal path (row 0) ---"')
w('  echo "  V(m0_iout_0)  = " $&V(m0_iout_0)  "  (mod0 KCL bus; target ≈0.468)"')
w('  echo "  V(m1_inp_0)   = " $&V(m1_inp_0)   "  (PMOS SF out → mod1 col; target ≈1.14)"')
w('  echo "  V(m1_iout_0)  = " $&V(m1_iout_0)  "  (mod1 KCL bus; target ≈0.468 after §72 fix)"')
w('  echo "  V(m2_inp_0)   = " $&V(m2_inp_0)   "  (PMOS SF out → mod2 col)"')
w('  echo "  V(m2_iout_0)  = " $&V(m2_iout_0)  "  (mod2 KCL bus)"')
w('  echo "  V(m3_inp_0)   = " $&V(m3_inp_0)   "  (PMOS SF out → mod3 col)"')
w('  echo "  V(m3_iout_0)  = " $&V(m3_iout_0)  "  (mod3 KCL bus, chip top output)"')
w()
w("  * Ascending level shifts (PMOS SF: expect POSITIVE ~+0.65V)")
w("  let shift_01 = V(m1_inp_0) - V(m0_iout_0)")
w("  let shift_12 = V(m2_inp_0) - V(m1_iout_0)")
w("  let shift_23 = V(m3_inp_0) - V(m2_iout_0)")
w('  echo "  Level shift link01 (PMOS SF): " $&shift_01 "V  (expect +0.65V: SF raises)"')
w('  echo "  Level shift link12 (PMOS SF): " $&shift_12 "V"')
w('  echo "  Level shift link23 (PMOS SF): " $&shift_23 "V"')
w('  echo ""')
w()
w("  * Descending prediction path")
w('  echo "  --- Descending prediction path ---"')
w('  echo "  V(m2_pred_0) = " $&V(m2_pred_0)')
w('  echo "  V(m1_pred_0) = " $&V(m1_pred_0)')
w('  echo "  V(m0_pred_0) = " $&V(m0_pred_0)')
w('  echo ""')
w()
w("  * Error flags")
w('  echo "  --- Error flags row 0 (HIGH = fires) ---"')
w('  echo "  ierr_m0_0 = " $&V(ierr_m0_0)')
w('  echo "  ierr_m1_0 = " $&V(ierr_m1_0)')
w('  echo "  ierr_m2_0 = " $&V(ierr_m2_0)')
w('  echo "  ierr_m3_0 = " $&V(ierr_m3_0) "  (i_pred=VSS → always HIGH)"')
w('  echo ""')
w()
w("  * PASS/FAIL: PMOS SF raises voltage (positive shift)")
w("  if shift_01 > 0")
w('    echo "  PASS: link01 shift positive (PMOS SF raises)"')
w("  else")
w('    echo "  WARN: link01 shift non-positive — check PMOS SF"')
w("  end")
w("  if shift_12 > 0")
w('    echo "  PASS: link12 shift positive"')
w("  else")
w('    echo "  WARN: link12 shift non-positive"')
w("  end")
w("  if shift_23 > 0")
w('    echo "  PASS: link23 shift positive"')
w("  else")
w('    echo "  WARN: link23 shift non-positive"')
w("  end")
w()
w("  * Check upper diff pairs receive sufficient input voltage")
w("  if V(m1_inp_0) > 0.6")
w('    echo "  PASS: mod1 inp > 0.6V (PMOS SF spatial fix working)"')
w("  else")
w('    echo "  WARN: mod1 inp too low — spatial pipeline may be dead"')
w("  end")
w()
w("  * §72 fix check: mod1 KCL bus alive (not collapsed to 0V or rail)")
w("  * NOTE: V(m1_iout) < V(m0_iout) is EXPECTED in untrained state — upper-layer Vcm")
w("  * is 1.14V vs Vw=0.75V, pushing MN3 into subthreshold (lower tail current).")
w("  * Hebbian learning would raise Vw in upper layers to restore proper biasing.")
w("  if V(m1_iout_0) > 0.05")
w('    echo "  PASS: mod1 iout > 0.05V — cascade alive (reduced gain expected, §72 bias note)"')
w("  else")
w('    echo "  WARN: mod1 iout < 0.05V — cascade may be dead"')
w("  end")
w()
w("  * §72 fix check: vcm_upper should match m1_inp at balance (within 0.1V)")
w("  let vcmu_err = abs(V(vcm_upper_01) - V(m1_inp_0))")
w("  if vcmu_err < 0.1")
w('    echo "  PASS: vcm_upper ≈ m1_inp (§72 reference SF tracking correctly)"')
w("  else")
w('    echo "  WARN: vcm_upper offset " $&vcmu_err "V from m1_inp — check ncm_iout bias"')
w("  end")
w()
w("  if V(ierr_m3_0) > 0.9")
w('    echo "  PASS: mod3 ierr_dig HIGH (top layer fires)"')
w("  else")
w('    echo "  WARN: mod3 ierr_dig LOW"')
w("  end")
w()
w("  write output/t1_4layer_op.raw")
w('  echo "  Saved: output/t1_4layer_op.raw"')
w()

# ── T2: DC sweep ─────────────────────────────────────────────────────────────
w("  * ──────────────────────────────────────────────────────────────────────────")
w("  * T2: DC sweep — raw_inp_0 ±50mV, signal gain through 4 layers")
w("  * ──────────────────────────────────────────────────────────────────────────")
w('  echo ""')
w('  echo "======================================================"')
w('  echo " T2: DC sweep — ascending signal gain"')
w('  echo "======================================================"')
w()
w("  dc Vinp0 0.85 0.95 0.005")
w()
for lo, hi, node in [
    ("0.86", "0.94", "m0_iout_0"),
    ("0.86", "0.94", "m1_inp_0"),
    ("0.86", "0.94", "m1_iout_0"),
    ("0.86", "0.94", "m2_inp_0"),
    ("0.86", "0.94", "m2_iout_0"),
    ("0.86", "0.94", "m3_inp_0"),
    ("0.86", "0.94", "m3_iout_0"),
]:
    safe = node.replace("_", "")
    w(f"  meas dc V{safe}_lo  FIND V({node})  WHEN V(raw_inp_0)={lo} CROSS=1")
    w(f"  meas dc V{safe}_hi  FIND V({node})  WHEN V(raw_inp_0)={hi} CROSS=1")
w()

nodes = ["m0_iout_0", "m1_inp_0", "m1_iout_0", "m2_inp_0",
         "m2_iout_0", "m3_inp_0", "m3_iout_0"]
for node in nodes:
    safe = node.replace("_", "")
    w(f"  let dV_{safe} = V{safe}_hi - V{safe}_lo")
    w(f'  echo "  V({node}) swing over 80mV: " $&dV_{safe} " V"')
w()
w('  echo ""')
for label, n_out, n_in in [
    ("mod0 gain (raw→iout)",  "m0_iout_0", None),
    ("link01 SF gain",        "m1_inp_0",  "m0_iout_0"),
    ("mod1 gain (inp→iout)",  "m1_iout_0", "m1_inp_0"),
    ("link12 SF gain",        "m2_inp_0",  "m1_iout_0"),
    ("mod2 gain (inp→iout)",  "m2_iout_0", "m2_inp_0"),
    ("link23 SF gain",        "m3_inp_0",  "m2_iout_0"),
    ("mod3 gain (inp→iout)",  "m3_iout_0", "m3_inp_0"),
]:
    s_out = n_out.replace("_", "")
    if n_in is not None:
        s_in = n_in.replace("_", "")
        w(f"  let gain_{s_out} = dV_{s_out} / dV_{s_in}")
        w(f'  echo "  {label}: " $&gain_{s_out}')
    else:
        w(f"  let gain_{s_out} = dV_{s_out} / 0.08")
        w(f'  echo "  {label}: " $&gain_{s_out}')
w()
w("  let abs_swing_m3 = abs(dV_m3iout0)")
w("  if abs_swing_m3 > 0.001")
w('    echo "  PASS: signal propagates through all 4 layers"')
w("  else")
w('    echo "  FAIL: no signal at mod3 — check PMOS SF ascending path"')
w("  end")
w()
w("  wrdata output/t2_4layer_sweep.csv V(raw_inp_0) V(m0_iout_0) V(m1_inp_0) V(m1_iout_0) V(m2_inp_0) V(m2_iout_0) V(m3_inp_0) V(m3_iout_0)")
w("  write  output/t2_4layer_sweep.raw")
w('  echo "  Saved: output/t2_4layer_sweep.csv  output/t2_4layer_sweep.raw"')
w()

# ── T3: Transient ─────────────────────────────────────────────────────────────
w("  * ──────────────────────────────────────────────────────────────────────────")
w("  * T3: Transient — Hebbian write on mod0 row 0")
w("  * ──────────────────────────────────────────────────────────────────────────")
w('  echo ""')
w('  echo "======================================================"')
w('  echo " T3: Transient — Hebbian write mod0 row0"')
w('  echo "======================================================"')
w()
w("  alter @vinp0[dc] = 1.1")
w()
w("  tran 0.5n 120n uic")
w()
w("  meas tran Vw_t110    FIND V(xmod0.xarray.vw_0_0)  AT=110n")
w("  meas tran Vw_t0      FIND V(xmod0.xarray.vw_0_0)  AT=1n")
w("  meas tran Verr_t60   FIND V(ierr_m0_0)              AT=60n")
w("  meas tran Vwe_t60    FIND V(we_m0_0)                AT=60n")
w()
w('  echo "  V(we_m0_0) at t=60ns:   " $&Vwe_t60  "  (expect 1.8V)"')
w('  echo "  V(ierr_m0_0) at t=60ns: " $&Verr_t60')
w('  echo "  V(vw_0_0) t=1n:   " $&Vw_t0')
w('  echo "  V(vw_0_0) t=110n: " $&Vw_t110')
w()
w("  let dVw = Vw_t110 - Vw_t0")
w('  echo "  Delta Vw = " $&dVw " V"')
w()
w("  let dVw_abs = abs(dVw)")
w("  if dVw_abs > 1e-3")
w('    echo "  PASS: weight changed — Hebbian write functional"')
w("  else")
w('    echo "  NOTE: weight unchanged — ierr_dig or WE path may be blocked"')
w("  end")
w()
w("  wrdata output/t3_4layer_hebb.csv V(xmod0.xarray.vw_0_0) V(ierr_m0_0) V(we_m0_0) V(m0_iout_0)")
w("  write  output/t3_4layer_hebb.raw")
w('  echo "  Saved: output/t3_4layer_hebb.csv"')
w()
w('  echo ""')
w('  echo "======================================================"')
w('  echo " All 4-layer tests complete."')
w('  echo "======================================================"')
w()
w("  quit")
w()
w(".endc")
w()
w(".end")

# ─────────────────────────────────────────────────────────────────────────────
# Write output
# ─────────────────────────────────────────────────────────────────────────────
outfile = "tb_pcn_4layer.spice"
with open(outfile, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Generated {outfile} ({len(lines)} lines)")
