"""
gen_tb_2layer.py — generate a 2-layer integration testbench for any NR×NC module.

Usage:
    python3 gen_tb_2layer.py <N_rows> <N_cols>

Generates:  tb_pcn_2layer_{NR}x{NC}.spice

Tests:
  T1  Operating point  — V(iout_row), V(ascending SF output), ierr_dig level
  T2  Hebbian write    — WE pulse on row 0, col 0; verify ΔVw > 0
  T3  DC sweep         — col 0 swept ±50 mV; verify ascending-path gain > 0
"""

import sys

def gen(nr, nc):
    lines = []

    lines.append(f"""\
* =============================================================================
* tb_pcn_2layer_{nr}x{nc}.spice — 2-module {nr}×{nc} integration testbench
* Generated by gen_tb_2layer.py — regenerate with: python3 gen_tb_2layer.py {nr} {nc}
*
* Tests three signal paths:
*   T1 (op-point):  bias rails; V(m0_iout0); ascending SF output; ierr_dig level.
*   T2 (transient): Hebbian WE pulse on mod0 row0 col0 → verify ΔVw > 0.
*   T3 (DC sweep):  col0 swept ±50 mV around Vcm; ascending-path gain checked.
*
* Key new parameters vs proof-of-concept (16×32):
*   R_err = 6.25 kΩ (for {nc} cols); W_MPG = 32 µm
*   V_trip = I_MPG2 × R_err = 176 µA × 6.25 kΩ = 1.1 V  (above VDD/2=0.9V → suppress)
*   Expected V(iout_row): lower than 1.031V (16×32) due to doubled column load.
*   Expected SF output = V(iout_row) − Vgs_SF; bandwidth invariant τ = 28 ns.
* =============================================================================

.title PCN 2-layer {nr}x{nc} integration testbench

.lib "$PDK_ROOT/sky130A/libs.tech/ngspice/sky130.lib.spice" tt
.include "pcn_mac_cell.spice"
.include "layer_link.spice"
.include "pcn_array_{nr}x{nc}.spice"
.include "pcn_module_{nr}x{nc}.spice"

* ── Simulation options ────────────────────────────────────────────────────────
.options RELTOL=1e-3 ABSTOL=1e-12 VNTOL=1e-6 GMIN=1e-10 METHOD=gear

* ── Supplies and bias rails ───────────────────────────────────────────────────
Vdd     vdd      0   DC 1.8
Vcm     vcm      0   DC 0.9
Vbn     vbias_n  0   DC 0.760
Vbp     vbias_p  0   DC 1.2
Vpi     vpi      0   DC 0.65

* ── Column 0 input (row 0 test stimulus) ─────────────────────────────────────
* inp_col_0 of mod0 gets its own source so T2/T3 can drive it independently.
* All other inputs (col 1..{nc-1} inp and all inn) tied directly to vcm node.
* inn_col_0 is also vcm (single-ended drive: differential = Vinp0 − Vcm).
Vinp0  m0_inp0  0  DC 0.9

* ── Write-enable row 0 pulse for T2 ──────────────────────────────────────────
* 20 ns pulse starting at t=50 ns; all other WE rows held low.
Vwe0  m0_we0  0  PULSE(0 1.8 50n 1n 1n 20n 200n)
""")

    # ── Module 0 instantiation ──────────────────────────────────────────────
    # Port order: inp_col_c inn_col_c × NC | iout_row × NR | i_pred × NR |
    #             ierr_dig × NR | we_row × NR | vpi × NR | vbias_p vbias_n vcm vdd vss
    lines.append(f"* ── Module 0 (lower) ─────────────────────────────────────────────────────────")
    lines.append(f"Xmod0")
    col_ports = ["m0_inp0  vcm"] + ["vcm  vcm"] * (nc - 1)
    for i, cp in enumerate(col_ports):
        lines.append(f"+ {cp}")
    iout = "  ".join(f"m0_iout{r}" for r in range(nr))
    lines.append(f"+ {iout}")
    ipred = "  ".join("0" for _ in range(nr))
    lines.append(f"+ {ipred}")
    ierr = "  ".join(f"m0_err{r}" for r in range(nr))
    lines.append(f"+ {ierr}")
    # WE: row 0 = m0_we0; rest = 0
    we = ["m0_we0"] + ["0"] * (nr - 1)
    we_str = "  ".join(we)
    lines.append(f"+ {we_str}")
    vpi_row = "  ".join("vpi" for _ in range(nr))
    lines.append(f"+ {vpi_row}")
    lines.append(f"+ vbias_p  vbias_n  vcm  vdd  0")
    lines.append(f"+ pcn_module_{nr}x{nc}")
    lines.append("")

    # ── Module 1 instantiation ──────────────────────────────────────────────
    lines.append(f"* ── Module 1 (upper) ─────────────────────────────────────────────────────────")
    lines.append(f"* Inputs driven by layer_link ascending source followers (m1_inp_r nodes).")
    lines.append(f"* i_pred = 0 (VSS): no top-layer supervision → unsupervised error always HIGH.")
    lines.append(f"Xmod1")
    for r in range(nr):
        lines.append(f"+ m1_inp{r}  vcm")
    lines.append(f"+ {iout.replace('m0_iout', 'm1_iout')}")
    lines.append(f"+ {ipred}")
    lines.append(f"+ {ierr.replace('m0_err', 'm1_err')}")
    lines.append(f"+ {'  '.join('0' for _ in range(nr))}")
    lines.append(f"+ {vpi_row}")
    lines.append(f"+ vbias_p  vbias_n  vcm  vdd  0")
    lines.append(f"+ pcn_module_{nr}x{nc}")
    lines.append("")

    # ── Layer_link instantiation ────────────────────────────────────────────
    lines.append(f"* ── Layer link ({nr} rows) ────────────────────────────────────────────────────")
    lines.append(f"* Ascending: m0_iout_r → SF → m1_inp_r")
    lines.append(f"* Descending: m1_iout_r gates XMPRED → sinks from m0_i_pred (=m0_i_err) nodes")
    lines.append(f"Xlink")
    for r in range(nr):
        lines.append(f"+ m0_iout{r}")
    for r in range(nr):
        lines.append(f"+ m1_inp{r}")
    # i_pred_lower: these are the i_pred ports of mod0 — but we wired them to 0 above.
    # The layer_link drives them; set them to internal node m0_lpred_r.
    # Actually: the layer_link i_pred ports connect to the same nodes as mod0's i_pred.
    # In tb_pcn_2layer_4x4, m0_pred0..3 are connected to BOTH Xmod0's i_pred ports AND Xlink's i_pred ports.
    # Xmod0 i_pred is wired to 0 (VSS) in this testbench? No — look again at 4x4:
    # Xmod0 has i_pred = m0_pred0..3, and Xlink also has i_pred = m0_pred0..3.
    # But in my code above I wired mod0 i_pred to "0". That's wrong for the connected testbench.
    # Let me fix: use m0_pred_r nodes for both mod0 i_pred and link i_pred_lower.
    # I'll re-do the mod0 and mod1 instantiations below.
    pass

    # Re-do correctly with connected nodes
    lines = []

    lines.append(f"""\
* =============================================================================
* tb_pcn_2layer_{nr}x{nc}.spice — 2-module {nr}×{nc} integration testbench
* Generated by gen_tb_2layer.py — regenerate with: python3 gen_tb_2layer.py {nr} {nc}
*
* Tests three signal paths:
*   T1 (op-point):  bias rails; V(m0_iout0); ascending SF output; ierr_dig.
*   T2 (transient): Hebbian WE pulse on mod0 row0 col0 → verify ΔVw > 0.
*   T3 (DC sweep):  col0 swept ±50 mV around Vcm; ascending-path gain checked.
*
* New vs 16×32 proof-of-concept:
*   R_err = 6.25 kΩ (64 cols);  W_MPG = 32 µm
*   V_trip = 176 µA × 6.25 kΩ = 1.1 V  (> VDD/2=0.9 V → gate suppresses correctly)
*   V(iout_row) expected lower than 1.031V (more column load on KCL bus)
*   τ_KCL = R_err × C_KCL = 6.25kΩ × (64×70fF) = 6.25kΩ × 4.48pF = 28 ns ✓ (invariant)
* =============================================================================

.title PCN 2-layer {nr}x{nc} integration testbench

.lib "$PDK_ROOT/sky130A/libs.tech/ngspice/sky130.lib.spice" tt
.include "pcn_mac_cell.spice"
.include "layer_link.spice"
.include "pcn_array_{nr}x{nc}.spice"
.include "pcn_module_{nr}x{nc}.spice"

* ── Simulation options ────────────────────────────────────────────────────────
.options RELTOL=1e-3 ABSTOL=1e-12 VNTOL=1e-6 GMIN=1e-10 METHOD=gear

* ── Supplies and bias rails ───────────────────────────────────────────────────
Vdd     vdd      0   DC 1.8
Vcm     vcm      0   DC 0.9
Vbn     vbias_n  0   DC 0.760
Vbp     vbias_p  0   DC 1.2
Vpi     vpi      0   DC 0.65
Vcm_iout  ncm_iout  0  DC 0.468

* ── Column 0 stimulus for mod0 (row0, col0 test cell) ────────────────────────
* Only inp_col_0 of mod0 gets its own source. All other inp and all inn = vcm.
* inn_col_0 = vcm too: single-ended → differential = Vinp0 − 0.9V.
Vinp0  m0_inp0  0  DC 0.9

* ── Write-enable: row 0 gets a 20 ns pulse at t=50 ns for T2 ─────────────────
Vwe0  m0_we0  0  PULSE(0 1.8 50n 1n 1n 20n 200n)
""")

    # ── Module 0 ────────────────────────────────────────────────────────────
    lines.append("* ── Module 0 (lower) ─────────────────────────────────────────────────────────")
    lines.append("Xmod0")
    # column inputs: col0 = m0_inp0/vcm; rest = vcm/vcm
    lines.append(f"+ m0_inp0  vcm")
    for c in range(1, nc):
        lines.append(f"+ vcm  vcm")
    # iout_row
    for r in range(nr):
        lines.append(f"+ m0_iout{r}")
    # i_pred — connected to m0_pred_r nodes (shared with layer_link descending outputs)
    for r in range(nr):
        lines.append(f"+ m0_pred{r}")
    # ierr_dig
    for r in range(nr):
        lines.append(f"+ m0_err{r}")
    # we_row
    lines.append(f"+ m0_we0")
    for r in range(1, nr):
        lines.append(f"+ 0")
    # vpi
    for r in range(nr):
        lines.append(f"+ vpi")
    lines.append(f"+ vbias_p  vbias_n  vcm  vdd  0")
    lines.append(f"+ pcn_module_{nr}x{nc}")
    lines.append("")

    # ── Module 1 ────────────────────────────────────────────────────────────
    # Architectural note: layer_link produces NR ascending SF outputs but module
    # needs NC column pairs.  When NR < NC (e.g. 32 rows → 64 cols), the first NR
    # columns are driven by SF outputs; remaining NC-NR columns are tied to vcm
    # (zero differential — no contribution to dot product).
    lines.append("* ── Module 1 (upper) ─────────────────────────────────────────────────────────")
    lines.append(f"* {nr} ascending SF outputs drive col0..{nr-1}; col{nr}..{nc-1} tied to vcm.")
    lines.append(f"* i_pred=0 (VSS): top layer — no supervision above. WE disabled.")
    lines.append("Xmod1")
    # First NR column pairs: SF output as inp, nvcm_upper as inn
    # (nvcm_upper is driven by the reference PMOS SF inside layer_link, preserving the differential)
    for r in range(nr):
        lines.append(f"+ m1_inp{r}  nvcm_upper")
    # Remaining NC-NR column pairs: vcm/vcm (zero differential)
    for c in range(nc - nr):
        lines.append(f"+ vcm  vcm")
    for r in range(nr):
        lines.append(f"+ m1_iout{r}")
    for r in range(nr):
        lines.append(f"+ 0")            # i_pred = VSS (top layer, no supervision)
    for r in range(nr):
        lines.append(f"+ m1_err{r}")
    for r in range(nr):
        lines.append(f"+ 0")            # WE disabled for mod1 in this test
    for r in range(nr):
        lines.append(f"+ vpi")
    lines.append(f"+ vbias_p  vbias_n  vcm  vdd  0")
    lines.append(f"+ pcn_module_{nr}x{nc}")
    lines.append("")

    # ── Layer_link ──────────────────────────────────────────────────────────
    lines.append(f"* ── Layer link ({nr} rows) ────────────────────────────────────────────────────")
    lines.append(f"* Ascending:  m0_iout_r → PMOS SF (+0.67V) → m1_inp_r  (§71)")
    lines.append(f"* Reference:  ncm_iout(0.468V) → ref PMOS SF → nvcm_upper(≈1.14V) → m1 inn_col")
    lines.append(f"* Descending: m1_iout_r → ngate_pred (R-divider) → XMPRED → m0_pred_r")
    lines.append(f"Xlink")
    for r in range(nr):
        lines.append(f"+ m0_iout{r}")
    for r in range(nr):
        lines.append(f"+ m1_inp{r}")
    for r in range(nr):
        lines.append(f"+ m0_pred{r}")   # descending prediction current output
    for r in range(nr):
        lines.append(f"+ m1_iout{r}")   # upper module KCL bus (gates XMPRED)
    lines.append(f"+ nvcm_upper  ncm_iout  vbias_n  vdd  0")
    lines.append(f"+ layer_link_{nr}")
    lines.append("")

    # ── Nodesets ─────────────────────────────────────────────────────────────
    lines.append("* ── Nodesets (convergence seeds) ────────────────────────────────────────────")
    lines.append("* V(iout_row): balanced OP ≈ 0.47V (current_sub XMPS1 loads bus below Vcm; §70)")
    lines.append("* Using 0.47V as starting guess; SPICE will find actual value.")
    for r in range(nr):
        lines.append(f".nodeset V(m0_iout{r})=0.47  V(m1_iout{r})=0.47")
    lines.append("")
    lines.append("* PMOS SF raises voltage: V(inp_upper) ≈ V(iout_lower) + |Vgs_P| ≈ 0.47 + 0.67 = 1.14V (§71)")
    for r in range(nr):
        lines.append(f".nodeset V(m1_inp{r})=1.14")
    lines.append(f".nodeset V(nvcm_upper)=1.14")
    lines.append("")
    lines.append("* Prediction nodes: near 0V initially (XMPRED in triode)")
    for r in range(nr):
        lines.append(f".nodeset V(m0_pred{r})=0.05")
    lines.append("")
    lines.append("* Error nodes (i_err, internal): small positive — R_err × I_MPG2 ≈ 1.1V")
    lines.append("* At untrained state XMPRED≈off, V(i_err) ≈ I_MPG2 × R_err = 1.1V (suppressed)")
    for r in range(nr):
        lines.append(f".nodeset V(xmod0.i_err_{r})=1.1")
        lines.append(f".nodeset V(xmod1.i_err_{r})=1.1")
    lines.append("")
    lines.append("* Weights: nodeset ALL cells to 0.75V (required — GMIN pulls ungated nodes to VSS)")
    for r in range(nr):
        for c in range(nc):
            lines.append(f".nodeset V(xmod0.xarray.vw_{r}_{c})=0.75")
            lines.append(f".nodeset V(xmod1.xarray.vw_{r}_{c})=0.75")
    lines.append("")
    lines.append("* iwrite nodes: float when WE=0; seed at Vcm")
    for r in range(nr):
        for c in range(nc):
            lines.append(f".nodeset V(xmod0.xarray.iwrite_{r}_{c})=0.9")
            lines.append(f".nodeset V(xmod1.xarray.iwrite_{r}_{c})=0.9")
    lines.append("")

    # ── Initial conditions for weight capacitors ──────────────────────────
    lines.append("* ── Weight initial conditions (.ic) ─────────────────────────────────────────")
    lines.append("* Set all 2×NR×NC weight caps to 0.75V for clean operating-point start.")
    for mod in ["xmod0", "xmod1"]:
        for r in range(nr):
            # Chunk per row for readability
            for c in range(nc):
                lines.append(f".ic V({mod}.xarray.vw_{r}_{c})=0.75")
    lines.append("")

    # ── .control block ───────────────────────────────────────────────────────
    lines.append("""\
* =============================================================================
.control

  set filetype = ascii

  * ──────────────────────────────────────────────────────────────────────────
  * T1: Operating point
  * Key new measurement: V(iout_row) for 64-column array.
  * ──────────────────────────────────────────────────────────────────────────
  echo ""
  echo "======================================================"
  echo " T1: Operating point — bias rails and signal levels"
  echo "======================================================"

  op

  echo "  V(vbias_n) = " $&V(vbias_n)  " V  (target: 0.760)"
  echo "  V(vcm)     = " $&V(vcm)      " V  (target: 0.900)"
  echo "  V(vpi)     = " $&V(vpi)      " V  (target: 0.650)"
  echo ""
  echo "  V(m0_iout0)   = " $&V(m0_iout0)   " V  (KCL bus; expect ~0.47V balanced OP)"
  echo "  V(m1_iout0)   = " $&V(m1_iout0)   " V  (upper KCL bus; expect ~0.47V)"
  echo "  V(ncm_iout)   = " $&V(ncm_iout)   " V  (stiff reference; expect 0.468V)"
  echo "  V(nvcm_upper) = " $&V(nvcm_upper) " V  (ref PMOS SF output; expect ~1.14V)"
  echo "  V(m1_inp0)    = " $&V(m1_inp0)    " V  (signal PMOS SF; expect ~1.14V)"
  echo "  V(m0_pred0)   = " $&V(m0_pred0)   " V  (descending prediction; expect ~0V untrained)"
  echo ""
  echo "  V(m0_err0)  = " $&V(m0_err0)  " V  (mod0 ierr_dig; HIGH=suppressed, LOW=active)"
  echo "  V(m1_err0)  = " $&V(m1_err0)  " V  (mod1 ierr_dig; expect HIGH - no supervision)"
  echo ""

  let level_shift = V(m1_inp0) - V(m0_iout0)
  echo "  Ascending level shift (V(m1_inp0) - V(m0_iout0)) = " $&level_shift " V"
  echo "  (expect positive: PMOS SF raises voltage by +0.67V)"
  if level_shift > 0
    echo "  PASS: ascending path shifts upward (PMOS SF active)"
  else
    echo "  WARN: level shift negative or zero — check layer_link XMSF (should be PMOS SF)"
  end

  * Verify V_trip scaling: V(i_err) at untrained state should be ~1.1V (above VDD/2=0.9V)
  * This means ierr_dig should be LOW (suppressed) — gate correctly holds off
  let v_trip_ok = V(xmod0.i_err_0) - 0.9
  echo ""
  echo "  V(xmod0.i_err_0) = " $&V(xmod0.i_err_0) " V  (R_err=6.25k; target > 0.9V = suppressed)"
  if v_trip_ok > 0
    echo "  PASS: i_err above VDD/2 → precision gate suppressed correctly"
  else
    echo "  WARN: i_err below VDD/2 → check R_err/W_MPG scaling"
  end

  write output/t1_op_{nr}x{nc}.raw
  echo "  Saved: output/t1_op_{nr}x{nc}.raw"


  * ──────────────────────────────────────────────────────────────────────────
  * T2: Transient — Hebbian weight update on mod0 row0 col0
  * ──────────────────────────────────────────────────────────────────────────
  echo ""
  echo "======================================================"
  echo " T2: Hebbian write — mod0 row0 col0"
  echo "======================================================"

  * Raise col0 above Vcm to drive positive differential → LTP attempt
  alter @vinp0[dc] = 1.1

  * uic: use .ic values (Vw=0.75V) as transient initial conditions, not the DC OP result.
  * Without uic, .ic is ignored and the transient starts from the DC OP (Vw≈0V).
  tran 0.5n 150n uic

  * Measure weight at t=1ns (initial IC) and t=120ns (after WE pulse at t=50-70ns).
  meas tran Vw_t1     FIND V(xmod0.xarray.vw_0_0)  AT=1n
  meas tran Vw_t120   FIND V(xmod0.xarray.vw_0_0)  AT=120n
  meas tran Verr_t60  FIND V(m0_err0)               AT=60n
  meas tran Vwe_t60   FIND V(m0_we0)                AT=60n

  echo "  V(vw_0_0)  at   1ns = " $&Vw_t1    " V  (from .ic; should be 0.75V)"
  echo "  V(m0_err0) at  60ns = " $&Verr_t60 " V  (HIGH during write = gate open)"
  echo "  V(m0_we0)  at  60ns = " $&Vwe_t60  " V  (should be 1.8V)"
  echo "  V(vw_0_0)  at 120ns = " $&Vw_t120  " V"
  let dVw = Vw_t120 - Vw_t1
  echo "  Delta Vw = " $&dVw " V"
  if abs(dVw) > 1e-4
    echo "  PASS: Hebbian write functional"
  else
    echo "  NOTE: weight unchanged — check ierr_dig and write path"
  end

  write output/t2_tran_{nr}x{nc}.raw
  wrdata output/t2_tran_{nr}x{nc}.csv v(xmod0.xarray.vw_0_0) v(m0_err0) v(m0_we0) v(m0_iout0)
  echo "  Saved: output/t2_tran_{nr}x{nc}.raw  output/t2_tran_{nr}x{nc}.csv"


  * ──────────────────────────────────────────────────────────────────────────
  * T3: DC sweep — ascending layer-link gain
  * ──────────────────────────────────────────────────────────────────────────
  echo ""
  echo "======================================================"
  echo " T3: DC sweep — ascending signal transfer"
  echo "======================================================"

  alter @vinp0[dc] = 0.9

  dc vinp0 0.85 0.95 0.005

  meas dc Viout_lo  FIND V(m0_iout0) WHEN V(m0_inp0)=0.86 CROSS=1
  meas dc Viout_hi  FIND V(m0_iout0) WHEN V(m0_inp0)=0.94 CROSS=1
  meas dc Vinp1_lo  FIND V(m1_inp0)  WHEN V(m0_inp0)=0.86 CROSS=1
  meas dc Vinp1_hi  FIND V(m1_inp0)  WHEN V(m0_inp0)=0.94 CROSS=1

  let d_iout = Viout_hi - Viout_lo
  let d_inp1 = Vinp1_hi - Vinp1_lo

  echo "  V(m0_iout0) at 0.86V in: " $&Viout_lo "  at 0.94V: " $&Viout_hi
  echo "  KCL bus swing over 80mV input: " $&d_iout " V"
  echo "  V(m1_inp0)  at 0.86V in: " $&Vinp1_lo "  at 0.94V: " $&Vinp1_hi
  echo "  Ascending SF swing over 80mV input: " $&d_inp1 " V"

  if abs(d_inp1) > 0.001
    echo "  PASS: ascending signal propagates through layer_link"
  else
    echo "  WARN: m1_inp0 unresponsive — check layer_link ascending path"
  end

  write output/t3_dc_{nr}x{nc}.raw
  wrdata output/t3_dc_{nr}x{nc}.csv v(m0_inp0) v(m0_iout0) v(m1_inp0) v(m0_pred0)
  echo "  Saved: output/t3_dc_{nr}x{nc}.raw  output/t3_dc_{nr}x{nc}.csv"

  echo ""
  echo "======================================================"
  echo " All tests complete"
  echo "======================================================"

  quit

.endc

.end
""")

    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: python3 {sys.argv[0]} <N_rows> <N_cols>")
        sys.exit(1)
    nr, nc = int(sys.argv[1]), int(sys.argv[2])
    out = f"tb_pcn_2layer_{nr}x{nc}.spice"
    with open(out, "w") as f:
        f.write(gen(nr, nc))
    print(f"Written: {out}")
